name: Bgm-Data-Sync

on:
  # 触发条件设置：手动触发和定时触发
  workflow_dispatch:  # 也支持手动触发
  # 定时触发
  schedule:
    - cron: "45 10 * * *"

jobs:
  bgm-sync:
    runs-on: ubuntu-latest
    name: 每日同步BGM收藏卡片
    steps:
      - name: Bgm Collection Card
        id: bgm
        uses: xiaoyvyv/bangumi-action@v1.1.17
        with:
          github-token: '${{secrets.GITHUB_TOKEN}}'
          bgm-user-id: 'azusacat'
          bgm-img-path: 'bgm/card.svg'

      - name: Get the output image url
        run: echo "图片生成的链接地址 ${{ steps.bgm.outputs.message }}"
